CREATE TABLE IF NOT EXISTS USERS (
    USER_ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS CUSTOMERS (
    CUSTOMER_ID SERIAL PRIMARY KEY,
    DATE_OF_BIRTH DATE,
    ADDRESS VARCHAR(255),
    USER_ID INT NOT NULL UNIQUE
--    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TRAINING_TYPES (
    TRAINING_TYPE_ID SERIAL PRIMARY KEY,
    TRAINING_TYPE_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TRAINERS (
    TRAINER_ID SERIAL PRIMARY KEY,
    TRAINING_TYPE_ID INT,
    USER_ID INT NOT NULL UNIQUE
--    FOREIGN KEY (TrainingTypeID) REFERENCES TrainingTypes(TrainingTypeID),
--    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TRAININGS (
    TRAINING_ID SERIAL PRIMARY KEY,
    CUSTOMER_ID INT,
    TRAINER_ID INT,
    TRAINING_NAME VARCHAR(255) NOT NULL,
    TRAINING_TYPE_ID INT,
    TRAINING_DATE DATE NOT NULL,
    TRAINING_DURATION INT NOT NULL
--    FOREIGN KEY (TrainingTypeID) REFERENCES TrainingTypes(TrainingTypeID),
--    FOREIGN KEY (TrainerID) REFERENCES Trainers(TrainerID),
--    FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID) ON DELETE CASCADE
);

--CREATE TABLE IF NOT EXISTS Customers_Trainers (
--    CustomerID INT,
--    TrainerID INT,
--    PRIMARY KEY (CustomerID, TrainerID),
--    FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID) ON DELETE CASCADE,
--    FOREIGN KEY (TrainerID) REFERENCES Trainers(TrainerID) ON DELETE CASCADE
--);


--CREATE TABLE IF NOT EXISTS Trainings_Customers (
--    TrainingID INT,
--    CustomerID INT,
--    PRIMARY KEY (TrainingID, CustomerID),
--    FOREIGN KEY (TrainingID) REFERENCES Trainings(TrainingID),
--    FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID),
--    UNIQUE (CustomerID)  -- Ensure that each Customer is associated with a specific Training only once
--);
